### ISSUE TITLE
Widget Item Link Broken

### ISSUE THREAD

**Issue by cbachmeier** [web3bio/web3bio#96]
Looking at [my profile ](https://web3.bio/bachmeier.eth) I noticed the Github and Twitter widget items links did not properly link out. The Github widget went to `https://github.com/github.com` and the Twitter widget went to `https://twitter.com/twitter.com`. It looks like [item.link](https://github.com/web3bio/web3bio/blob/main/components/profile/WidgetItem.tsx#L31) might be the incorrect value.  You can see my ens configuration with the correct github url [here](https://app.ens.domains/bachmeier.eth).  

See web3bio screenshot of incorrectly linked github widget below:
<img width="1728" alt="Screen Shot 2023-05-28 at 08 13 35 " src="https://github.com/web3bio/web3bio/assets/11512321/07ce6d7c-a736-4eb3-b5fb-bda652404ce2">

**Comment by picturepan2** [comment]
@cbachmeier Hi, we will improve the results in our Web3 Profile API. Your GitHub record in the ENS should be `cbachmeier` rather than `https://github.com/cbachmeier` which currently results in `https://github.com/https://github.com/cbachmeier`.

**Comment by picturepan2** [comment]
@cbachmeier Hi we have fixed the link extract issue in this PR and will be merged to the production soon. https://github.com/web3bio/web3bio-profile-api/pull/24
